version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "IRE-Mudlet-Mapping/CrowdmapPlatform*"
        update-types: ["version-update:semver-major"]
