name: JSON map diff

on: pull_request_target

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  diff:
    uses: IRE-Mudlet-Mapping/CrowdmapPlatform/.github/workflows/json-diff.yml@v1
